In [1]:
pwd

u'C:\\pydev\\ML\\Ch02'

In [2]:
import kNN

In [3]:
dataSet, labels = kNN.createDataSet()

In [4]:
print(dataSet)
print(labels)

[[ 1.   1.1]
 [ 1.   1. ]
 [ 0.   0. ]
 [ 0.   0.1]]
['A', 'A', 'B', 'B']


In [5]:
dataSetSize = dataSet.shape[0]; dataSetSize

4L

In [21]:
inX = [0, 0.5]

In [22]:
np.tile(inX, (dataSetSize, 1))

array([[ 0. ,  0.5],
       [ 0. ,  0.5],
       [ 0. ,  0.5],
       [ 0. ,  0.5]])

In [23]:
import numpy as np

In [24]:
diffMat = np.tile(inX, (dataSetSize, 1)) - dataSet; diffMat

array([[-1. , -0.6],
       [-1. , -0.5],
       [ 0. ,  0.5],
       [ 0. ,  0.4]])

In [25]:
sqDiffMat = diffMat ** 2; sqDiffMat

array([[ 1.  ,  0.36],
       [ 1.  ,  0.25],
       [ 0.  ,  0.25],
       [ 0.  ,  0.16]])

In [26]:
sqDiffMat[:, 0] + sqDiffMat[:, 1]

array([ 1.36,  1.25,  0.25,  0.16])

In [27]:
sqDistances = sqDiffMat.sum(axis=1); sqDistances

array([ 1.36,  1.25,  0.25,  0.16])

In [28]:
distances = sqDistances ** 0.5; distances

array([ 1.16619038,  1.11803399,  0.5       ,  0.4       ])

In [29]:
sortedDistIndices = distances.argsort(); sortedDistIndices

array([3, 2, 1, 0], dtype=int64)

In [30]:
classCount = {}

In [31]:
k = 3
range(k)

[0, 1, 2]

In [32]:
i = 0

In [33]:
sortedDistIndices[i]

3

In [34]:
labels[sortedDistIndices[i]]

'B'

In [35]:
voteIlabel = labels[sortedDistIndices[i]]; voteIlabel

'B'

In [36]:
classCount[voteIlabel] = classCount.get(voteIlabel, 0) + 1

In [37]:
classCount

{'B': 1}

In [38]:
list(classCount.iteritems())

[('B', 1)]

In [39]:
import operator

In [40]:
operator.itemgetter(1)

In [41]:
sortedClassCount = sorted(classCount.iteritems(), key=operator.itemgetter(1), reverse=True)
sortedClassCount

[('B', 1)]

In [42]:
sortedClassCount[0]

('B', 1)

In [43]:
sortedClassCount[0][0]

'B'

In [44]:
reload(kNN)

<module 'kNN' from 'kNN.pyc'>

In [45]:
kNN.classify0([0, 0.5], dataSet, labels, 3)

'B'

In [46]:
kNN.classify0([0.8, 0.8], dataSet, labels)

TypeError: classify0() takes exactly 4 arguments (3 given)

### listing 2.2

In [47]:
filename = 'datingTestSet2.txt'

In [48]:
fr = open(filename)

IOError: [Errno 2] No such file or directory: 'datingTestSet2.txt'

In [49]:
fr.readlines()

NameError: name 'fr' is not defined

In [50]:
fr = open(filename)
numberOfLines = len(fr.readlines()); numberOfLines

IOError: [Errno 2] No such file or directory: 'datingTestSet2.txt'

In [51]:
returnMat = np.zeros((numberOfLines, 3)); returnMat

NameError: name 'numberOfLines' is not defined

In [52]:
classLabelVector = []

In [53]:
fr = open(filename)
index = 0

IOError: [Errno 2] No such file or directory: 'datingTestSet2.txt'

In [54]:
lines = fr.readlines()

NameError: name 'fr' is not defined

In [55]:
line = lines[2]; line

NameError: name 'lines' is not defined

In [56]:
line = line.strip(); line

NameError: name 'line' is not defined

In [57]:
listFromLine = line.split('\t'); listFromLine

NameError: name 'line' is not defined

In [58]:
returnMat[index, :] = listFromLine[:3]; returnMat

NameError: name 'listFromLine' is not defined

In [59]:
classLabelVector.append(int(listFromLine[-1])); classLabelVector

NameError: name 'listFromLine' is not defined

In [60]:
index += 1

NameError: name 'index' is not defined

In [61]:
reload(kNN)

<module 'kNN' from 'kNN.pyc'>

In [62]:
datingDataMat, datingLabels = kNN.file2matrix(filename)

IOError: [Errno 2] No such file or directory: 'datingTestSet2.txt'

In [63]:
print datingDataMat
print datingLabels

NameError: name 'datingDataMat' is not defined

In [64]:
mapping = {1: 'didnt like', 2: 'small doses', 3: 'large doses'}; mapping

{1: 'didnt like', 2: 'small doses', 3: 'large doses'}

In [65]:
mapping[datingLabels[0]]

NameError: name 'datingLabels' is not defined

In [66]:
[mapping[label] for label in datingLabels]

NameError: name 'datingLabels' is not defined

### 2.2.2 분석

In [67]:
import matplotlib
import matplotlib.pyplot as plt

ImportError: No module named matplotlib

In [68]:
fig = plt.figure()
ax = fig.add_subplot(111)

NameError: name 'plt' is not defined

In [69]:
ax.scatter(datingDataMat[:, 1], datingDataMat[:, 2])

NameError: name 'ax' is not defined

In [70]:
plt.show()

NameError: name 'plt' is not defined

In [71]:
ax.scatter(datingDataMat[:, 1], datingDataMat[:, 2],
           15.0*np.array(datingLabels), 15.0*np.array(datingLabels))

NameError: name 'ax' is not defined

In [72]:
plt.show()

NameError: name 'plt' is not defined

In [73]:
%matplotlib inline

ImportError: No module named matplotlib

In [ ]:
fig = plt.figure()
ax = fig.add_subplot(111)
ax.scatter(datingDataMat[:, 0], datingDataMat[:, 1],
           15.0*np.array(datingLabels), 15.0*np.array(datingLabels))

In [ ]:
fig = plt.figure()
ax = fig.add_subplot(111)
ax.scatter(datingDataMat[:, 0], datingDataMat[:, 2],
           15.0*np.array(datingLabels), 15.0*np.array(datingLabels))

## 2.2.3 준비: 정규화

In [ ]:
reload(kNN)

In [ ]:
normMat, ranges, minVals = kNN.autoNorm(datingDataMat)

In [ ]:
print(normMat)

In [ ]:
print(ranges)

In [ ]:
print(minVals)

### 2.2.4 검사: 분류기 검사

In [74]:
reload(kNN)

<module 'kNN' from 'kNN.pyc'>

In [75]:
kNN.datingClassTest()

IOError: [Errno 2] No such file or directory: 'datingTestSet2.txt'

### 2.2.5 사용

In [76]:
reload(kNN)

<module 'kNN' from 'kNN.pyc'>

In [77]:
kNN.classifyPerson()

AttributeError: 'module' object has no attribute 'classifyPerson'

In [78]:
kNN.classifyPerson()

AttributeError: 'module' object has no attribute 'classifyPerson'

In [79]:
kNN.classifyPerson()

AttributeError: 'module' object has no attribute 'classifyPerson'